version: "3"

services:
  btc_api:
    container_name: btc_api
    restart: always
    build: ./btc_api
    expose:
      - "8000"
    command: gunicorn --workers 1 --bind :8000 app.wsgi:app

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - btc_api
